-- File generated by the BNF Converter (bnfc 2.9.3).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Parser.SkelLatte where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Parser.AbsLatte

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Parser.AbsLatte.Ident -> Result
transIdent x = case x of
  Parser.AbsLatte.Ident string -> failure x

transProgram :: Show a => Parser.AbsLatte.Program' a -> Result
transProgram x = case x of
  Parser.AbsLatte.Program _ topdefs -> failure x

transTopDef :: Show a => Parser.AbsLatte.TopDef' a -> Result
transTopDef x = case x of
  Parser.AbsLatte.TopFnDef _ fndef -> failure x
  Parser.AbsLatte.ClassDef _ ident classstmts -> failure x
  Parser.AbsLatte.ClassExtDef _ ident1 ident2 classstmts -> failure x

transClassStmt :: Show a => Parser.AbsLatte.ClassStmt' a -> Result
transClassStmt x = case x of
  Parser.AbsLatte.FnProp _ fndef -> failure x
  Parser.AbsLatte.AttrProp _ type_ ident -> failure x

transFnDef :: Show a => Parser.AbsLatte.FnDef' a -> Result
transFnDef x = case x of
  Parser.AbsLatte.FnDef _ type_ ident args block -> failure x

transArg :: Show a => Parser.AbsLatte.Arg' a -> Result
transArg x = case x of
  Parser.AbsLatte.Arg _ type_ ident -> failure x

transBlock :: Show a => Parser.AbsLatte.Block' a -> Result
transBlock x = case x of
  Parser.AbsLatte.Block _ stmts -> failure x

transStmt :: Show a => Parser.AbsLatte.Stmt' a -> Result
transStmt x = case x of
  Parser.AbsLatte.Empty _ -> failure x
  Parser.AbsLatte.BStmt _ block -> failure x
  Parser.AbsLatte.Decl _ type_ items -> failure x
  Parser.AbsLatte.Ass _ expr1 expr2 -> failure x
  Parser.AbsLatte.Incr _ ident -> failure x
  Parser.AbsLatte.Decr _ ident -> failure x
  Parser.AbsLatte.Ret _ expr -> failure x
  Parser.AbsLatte.VRet _ -> failure x
  Parser.AbsLatte.Cond _ expr stmt -> failure x
  Parser.AbsLatte.CondElse _ expr stmt1 stmt2 -> failure x
  Parser.AbsLatte.While _ expr stmt -> failure x
  Parser.AbsLatte.SExp _ expr -> failure x
  Parser.AbsLatte.For _ type_ ident expr stmt -> failure x

transItem :: Show a => Parser.AbsLatte.Item' a -> Result
transItem x = case x of
  Parser.AbsLatte.NoInit _ ident -> failure x
  Parser.AbsLatte.Init _ ident expr -> failure x

transType :: Show a => Parser.AbsLatte.Type' a -> Result
transType x = case x of
  Parser.AbsLatte.Int _ -> failure x
  Parser.AbsLatte.Str _ -> failure x
  Parser.AbsLatte.Bool _ -> failure x
  Parser.AbsLatte.Void _ -> failure x
  Parser.AbsLatte.List _ type_ -> failure x
  Parser.AbsLatte.ClassType _ ident -> failure x
  Parser.AbsLatte.Fun _ type_ types -> failure x

transExpr :: Show a => Parser.AbsLatte.Expr' a -> Result
transExpr x = case x of
  Parser.AbsLatte.EVar _ ident -> failure x
  Parser.AbsLatte.ELitInt _ integer -> failure x
  Parser.AbsLatte.ELitTrue _ -> failure x
  Parser.AbsLatte.ELitFalse _ -> failure x
  Parser.AbsLatte.ENewArr _ type_ expr -> failure x
  Parser.AbsLatte.ENewClass _ type_ -> failure x
  Parser.AbsLatte.EApp _ ident exprs -> failure x
  Parser.AbsLatte.EPropApp _ expr ident exprs -> failure x
  Parser.AbsLatte.EProp _ expr ident -> failure x
  Parser.AbsLatte.EArrGet _ expr1 expr2 -> failure x
  Parser.AbsLatte.ENullCast _ ident -> failure x
  Parser.AbsLatte.EString _ string -> failure x
  Parser.AbsLatte.Neg _ expr -> failure x
  Parser.AbsLatte.Not _ expr -> failure x
  Parser.AbsLatte.EMul _ expr1 mulop expr2 -> failure x
  Parser.AbsLatte.EAdd _ expr1 addop expr2 -> failure x
  Parser.AbsLatte.ERel _ expr1 relop expr2 -> failure x
  Parser.AbsLatte.EAnd _ expr1 expr2 -> failure x
  Parser.AbsLatte.EOr _ expr1 expr2 -> failure x

transAddOp :: Show a => Parser.AbsLatte.AddOp' a -> Result
transAddOp x = case x of
  Parser.AbsLatte.Plus _ -> failure x
  Parser.AbsLatte.Minus _ -> failure x

transMulOp :: Show a => Parser.AbsLatte.MulOp' a -> Result
transMulOp x = case x of
  Parser.AbsLatte.Times _ -> failure x
  Parser.AbsLatte.Div _ -> failure x
  Parser.AbsLatte.Mod _ -> failure x

transRelOp :: Show a => Parser.AbsLatte.RelOp' a -> Result
transRelOp x = case x of
  Parser.AbsLatte.LTH _ -> failure x
  Parser.AbsLatte.LE _ -> failure x
  Parser.AbsLatte.GTH _ -> failure x
  Parser.AbsLatte.GE _ -> failure x
  Parser.AbsLatte.EQU _ -> failure x
  Parser.AbsLatte.NE _ -> failure x
